// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi6D0HMHyDfj0XYUreGtgHePm-cicTK3c',
    appId: '1:763731811626:web:0cfab93f0288eb4ac45253',
    messagingSenderId: '763731811626',
    projectId: 'ecss-project',
    authDomain: 'ecss-project.firebaseapp.com',
    storageBucket: 'ecss-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAwPT3dhuerh0C3wgIq16lkTIdnIysgI',
    appId: '1:763731811626:android:62238ef90f8cb07bc45253',
    messagingSenderId: '763731811626',
    projectId: 'ecss-project',
    storageBucket: 'ecss-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATdZe-RUKRJIw9rTIXpIUjDnfdvOpaGbU',
    appId: '1:763731811626:ios:984fa28d49951a1ac45253',
    messagingSenderId: '763731811626',
    projectId: 'ecss-project',
    storageBucket: 'ecss-project.appspot.com',
    iosClientId: '763731811626-jjvvktskn3ad1ecqsqq5k22sclck8fg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.supportCompanuySelection',
  );
}
